name: Build Docker

on: push
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Build Container
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
